# ===============================
# DATABASE CONNECTION
# ===============================

# ===============================
# JPA / HIBERNATE
# ===============================

spring:
  datasource:
    url: jdbc:postgresql://${HOST}:${PORT}/${NAME}
    username: ${USER}
    password: ${PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true


# ===============================
# BOT SETTINGS
# ===============================

bot:
  name:
    ${BOT_NAME}
  pass:
    ${BOT_PASS}




